CREATE TABLE FILM_LETTERBOXD_STATS (FILM_ID TEXT PRIMARY KEY, FILM_WATCH_COUNT INTEGER, FILM_FAN_COUNT INTEGER, FILM_LIKES_COUNT INTEGER, FILM_REVIEW_COUNT INTEGER, FILM_LIST_COUNT INTEGER, FILM_RATING REAL, FILM_RATING_COUNT INTEGER, CREATED_AT);

CREATE TABLE FILM_STREAMING_SERVICES (FILM_ID TEXT, STREAMING_SERVICE_ABBR TEXT, STREAMING_SERVICE_FULL TEXT, CREATED_AT, PRICE, VALID [INTEGER]);

CREATE TABLE FILM_GENRE (FILM_ID TEXT PRIMARY KEY, FILM_GENRE TEXT NOT NULL, ALL_FILM_GENRES TEXT NOT NULL, CREATED_AT);

CREATE TABLE INGESTED(FILM_ID, CREATED_AT);

CREATE TABLE TMDB_ID(
	FILM_ID TEXT PRIMARY KEY,
	TMDB_ID TEXT NOT NULL
, CREATED_AT, VALID);

CREATE TABLE FILM_FINANCIALS (

	FILM_ID STRING PRIMARY KEY,
	FILM_BUDGET INTEGER,
	FILM_REVENUE INTEGER
	
, CREATED_AT);

CREATE TABLE FILM_TMDB_STATS (

	FILM_ID STRING PRIMARY KEY,
	FILM_POPULARITY FLOAT,
	FILM_VOTE_COUNT INTEGER,
	FILM_VOTE_AVERAGE FLOAT
	
, CREATED_AT);

CREATE TABLE FILM_LANGUAGE (

	FILM_ID STRING PRIMARY KEY,
	FILM_LANGUAGE STRING	
, CREATED_AT);

CREATE TABLE FILM_RELEASE_INFO (

	FILM_ID STRING PRIMARY KEY,
	FILM_RELEASE_DATE DATE,
	FILM_STATUS STRING
	
, CREATED_AT);

CREATE TABLE FILM_RUNTIME (

	FILM_ID STRING PRIMARY KEY,
	FILM_RUNTIME INTEGER
	
, CREATED_AT);

CREATE TABLE FILM_KEYWORDS (

	FILM_ID STRING,
	KEYWORD_ID STRING,
	KEYWORD STRING
	
, CREATED_AT);

CREATE TABLE FILM_CAST (

	FILM_ID STRING,
	PERSON_ID STRING,
	CHARACTER STRING,
	CAST_ORDER INTEGER
	
, CREATED_AT);

CREATE TABLE FILM_COLLECTIONS (

	FILM_ID STRING,
	COLLECTION_ID INTEGER,
	COLLECTION_NAME STRING
	
, CREATED_AT);

CREATE TABLE IMDB_ID (

	FILM_ID STRING PRIMARY KEY,
	IMDB_ID INTEGER
	
, CREATED_AT);

CREATE TABLE CONTENT_TYPE (

	FILM_ID STRING PRIMARY KEY,
	CONTENT_TYPE INTEGER
	
, CREATED_AT);

CREATE VIEW FILM_COLLECTIONS_VALID AS
SELECT

	 a.FILM_ID
	,b.FILM_TITLE
	,CASE WHEN COALESCE(c.FILM_RELEASE_DATE, '') = '' THEN '2099-09-09' ELSE c.FILM_RELEASE_DATE END AS RELEASE_DATE_CORRECTED
	,c.FILM_STATUS
	,a.COLLECTION_ID
	,a.COLLECTION_NAME
	,ROW_NUMBER() OVER (PARTITION BY a.COLLECTION_ID ORDER BY CASE WHEN COALESCE(c.FILM_RELEASE_DATE, '') = '' THEN '2099-09-09' ELSE c.FILM_RELEASE_DATE END) AS COLLECTION_NUM
	,CASE WHEN d.FILM_ID IS NULL THEN 0 ELSE 1 END AS WATCHED
	

FROM FILM_COLLECTIONS a

LEFT JOIN FILM_TITLE b
ON a.FILM_ID = b.FILM_ID

LEFT JOIN FILM_RELEASE_INFO c
ON a.FILM_ID = c.FILM_ID

LEFT JOIN WATCHED d 
ON a.FILM_ID = d.FILM_ID
--
WHERE a.COLLECTION_ID != -1
AND c.FILM_STATUS = 'Released'
AND DATE(c.FILM_RELEASE_DATE) < DATE('now');

CREATE VIEW COLLECTION_STATS AS 

WITH COLLECTION_LEVEL_TABLE AS (

SELECT
	 COLLECTION_ID
	,COLLECTION_NAME
	,COUNT(*) AS COLLECTION_SIZE
	,SUM(WATCHED) AS TOTAL_WATCHED
	,MAX(CASE WHEN WATCHED = 1 THEN COLLECTION_NUM ELSE 0 END) AS MAX_WATCHED
	
FROM FILM_COLLECTIONS_VALID

GROUP BY COLLECTION_ID
)

SELECT 

	 *
	,COLLECTION_SIZE - TOTAL_WATCHED AS FILMS_TO_COMPLETE
	,TOTAL_WATCHED*1.0 / COLLECTION_SIZE AS PERCENT_WATCHED
	,CASE WHEN TOTAL_WATCHED = COLLECTION_SIZE THEN 1 ELSE 0 END AS COLLECTION_COMPLETE


FROM COLLECTION_LEVEL_TABLE

ORDER BY FILMS_TO_COMPLETE ASC, COLLECTION_SIZE DESC;

CREATE VIEW FILMS_AVAILABLE_TO_STREAM 
AS
SELECT DISTINCT FILM_ID
FROM FILM_STREAMING_SERVICES
WHERE PRICE = 0;

CREATE TABLE FILM_CREW (
	FILM_ID,
	PERSON_ID,
	JOB,
	CREATED_AT
);

CREATE TABLE PERSON_INFO (
	PERSON_ID INTEGER PRIMARY KEY,
    PERSON_NAME STRING,
    IMDB_PERSON_ID STRING,
    GENDER INTEGER,
    DATE_OF_BIRTH STRING,
    DATE_OF_DEATH STRING,
    KNOWN_FOR_DEPARTMENT STRING,
    PLACE_OF_BIRTH STRING,
    PERSON_POPULARITY FLOAT
	VALID INTEGER
, VALID INTEGER, CREATED_AT);

CREATE TABLE FILM_URL_TITLE (
	FILM_ID STRING PRIMARY KEY,
	FILM_URL_TITLE STRING
, CREATED_AT);

CREATE VIEW ALL_FILMS 
AS 
WITH UNION_TABLE AS (

	SELECT FILM_ID
	FROM WATCHED
	UNION ALL
	SELECT FILM_ID
	FROM WATCHLIST
	
	)
	
SELECT

	DISTINCT FILM_ID

FROM UNION_TABLE a;

CREATE VIEW ALL_RELEASED_FILMS AS

WITH UNION_TABLE AS (

	SELECT a.FILM_ID
	FROM WATCHED a
	LEFT JOIN FILM_RELEASE_INFO b ON a.FILM_ID = b.FILM_ID
	WHERE b.FILM_STATUS = 'Released'
	AND DATE(CASE WHEN COALESCE(b.FILM_RELEASE_DATE, '') = '' THEN '2099-09-09' ELSE b.FILM_RELEASE_DATE END) < DATE('now')
	
	UNION ALL
	
	SELECT a.FILM_ID
	FROM WATCHLIST a
	LEFT JOIN FILM_RELEASE_INFO b ON a.FILM_ID = b.FILM_ID
	WHERE b.FILM_STATUS = 'Released'
	AND DATE(CASE WHEN COALESCE(b.FILM_RELEASE_DATE, '') = '' THEN '2099-09-09' ELSE b.FILM_RELEASE_DATE END) < DATE('now')
	
	)
	
SELECT

	DISTINCT FILM_ID
	
FROM UNION_TABLE;

CREATE VIEW EXPANDED_WATCHLIST AS
WITH WATCHLIST_UNION AS (

	SELECT
		
		 FILM_ID
		,0 AS SEEN
		
	FROM WATCHLIST
	
	UNION ALL
	
	SELECT
	
		  w.FILM_ID
		 ,1 AS SEEN
		
	FROM WATCHED w
	LEFT JOIN DIARY d
	ON w.FILM_ID = d.FILM_ID
	WHERE d.WATCH_DATE IS NULL
	
	)
	
SELECT

	 a.FILM_ID
	,MAX(a.SEEN) AS SEEN
	
FROM WATCHLIST_UNION a
INNER JOIN ALL_FEATURE_FILMS b
ON a.FILM_ID = b.FILM_ID
GROUP BY a.FILM_ID;

CREATE VIEW FILM_LAST_UPDATED AS 

SELECT

	 FILM_ID
	,AVG(DAYS_SINCE_LAST_UPDATE) AS MEAN_DAYS_SINCE_LAST_UPDATE
	
FROM FILM_LAST_UPDATED_DETAIL

GROUP BY FILM_ID;

CREATE VIEW ALL_FEATURE_FILMS AS 

SELECT

        DISTINCT a.FILM_ID

FROM ALL_FILMS a
LEFT JOIN FILM_RELEASE_INFO b ON a.FILM_ID = b.FILM_ID
LEFT JOIN FILM_RUNTIME c ON a.FILM_ID = c.FILM_ID
LEFT JOIN FILM_GENRE d ON a.FILM_ID = d.FILM_ID
LEFT JOIN CONTENT_TYPE e ON a.FILM_ID = e.FILM_ID
LEFT JOIN PERSONAL_RANKING f ON a.FILM_ID = f.FILM_ID

WHERE (
        e.CONTENT_TYPE = 'movie'
        AND b.FILM_STATUS = 'Released'
        AND DATE(CASE WHEN COALESCE(b.FILM_RELEASE_DATE, '') = '' THEN '2099-09-09' ELSE b.FILM_RELEASE_DATE END) < DATE('now')
        AND COALESCE(c.FILM_RUNTIME, 0) >= 60
        AND d.ALL_FILM_GENRES NOT LIKE '%tv-movie%'
        AND d.ALL_FILM_GENRES NOT LIKE '%documentary%'
        )
OR f.FILM_ID IS NOT NULL;

CREATE TABLE LOGGING (
    FILM_ID TEXT,
    TABLE_NAME TEXT,
    COLUMN_NAME TEXT,
    COLUMN_VALUE TEXT,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
, LOG_REASON);

CREATE VIEW FILM_LAST_UPDATED_DETAIL AS

WITH UNION_TABLE AS (

SELECT FILM_ID, 'CONTENT_TYPE' AS TABLE_NAME, ROUND(COALESCE(julianday('now') - julianday(CREATED_AT), 99), 0) AS DAYS_SINCE_LAST_UPDATE
FROM CONTENT_TYPE

UNION ALL

SELECT FILM_ID, 'FILM_CAST' AS TABLE_NAME, ROUND(AVG(DAYS_SINCE_LAST_UPDATE), 0) AS DAYS_SINCE_LAST_UPDATE 
FROM ( SELECT FILM_ID, ROUND(COALESCE(julianday('now') - julianday(CREATED_AT), 99), 0) AS DAYS_SINCE_LAST_UPDATE FROM FILM_CAST )
GROUP BY FILM_ID

UNION ALL 

SELECT FILM_ID, 'FILM_COLLECTIONS' AS TABLE_NAME, ROUND(COALESCE(julianday('now') - julianday(CREATED_AT), 99), 0) AS DAYS_SINCE_LAST_UPDATE
FROM FILM_COLLECTIONS

UNION ALL

SELECT FILM_ID, 'FILM_CREW' AS TABLE_NAME, ROUND(AVG(DAYS_SINCE_LAST_UPDATE), 0) AS DAYS_SINCE_LAST_UPDATE 
FROM ( SELECT FILM_ID, ROUND(COALESCE(julianday('now') - julianday(CREATED_AT), 99), 0) AS DAYS_SINCE_LAST_UPDATE FROM FILM_CREW )
GROUP BY FILM_ID

UNION ALL

SELECT FILM_ID, 'FILM_FINANCIALS' AS TABLE_NAME, ROUND(COALESCE(julianday('now') - julianday(CREATED_AT), 99), 0) AS DAYS_SINCE_LAST_UPDATE
FROM FILM_FINANCIALS

UNION ALL

SELECT FILM_ID, 'FILM_GENRE' AS TABLE_NAME, ROUND(COALESCE(julianday('now') - julianday(CREATED_AT), 99), 0) AS DAYS_SINCE_LAST_UPDATE
FROM FILM_GENRE

UNION ALL

SELECT FILM_ID, 'FILM_KEYWORDS' AS TABLE_NAME, ROUND(AVG(DAYS_SINCE_LAST_UPDATE), 0) AS DAYS_SINCE_LAST_UPDATE 
FROM ( SELECT FILM_ID, ROUND(COALESCE(julianday('now') - julianday(CREATED_AT), 99), 0) AS DAYS_SINCE_LAST_UPDATE FROM FILM_KEYWORDS )
GROUP BY FILM_ID

UNION ALL

SELECT FILM_ID, 'FILM_LANGUAGE' AS TABLE_NAME, ROUND(COALESCE(julianday('now') - julianday(CREATED_AT), 99), 0) AS DAYS_SINCE_LAST_UPDATE
FROM FILM_LANGUAGE

UNION ALL

SELECT FILM_ID, 'FILM_LETTERBOXD_STATS' AS TABLE_NAME, ROUND(COALESCE(julianday('now') - julianday(CREATED_AT), 99), 0) AS DAYS_SINCE_LAST_UPDATE
FROM FILM_LETTERBOXD_STATS

UNION ALL

SELECT FILM_ID, 'FILM_RELEASE_INFO' AS TABLE_NAME, ROUND(COALESCE(julianday('now') - julianday(CREATED_AT), 99), 0) AS DAYS_SINCE_LAST_UPDATE
FROM FILM_RELEASE_INFO

UNION ALL

SELECT FILM_ID, 'FILM_RUNTIME' AS TABLE_NAME, ROUND(COALESCE(julianday('now') - julianday(CREATED_AT), 99), 0) AS DAYS_SINCE_LAST_UPDATE
FROM FILM_RUNTIME

UNION ALL

SELECT FILM_ID, 'FILM_STREAMING_SERVICES' AS TABLE_NAME, ROUND(AVG(DAYS_SINCE_LAST_UPDATE), 0) AS DAYS_SINCE_LAST_UPDATE 
FROM ( SELECT FILM_ID, ROUND(COALESCE(julianday('now') - julianday(CREATED_AT), 99), 0) AS DAYS_SINCE_LAST_UPDATE FROM FILM_STREAMING_SERVICES )
GROUP BY FILM_ID

UNION ALL 

SELECT FILM_ID, 'FILM_TMDB_STATS' AS TABLE_NAME, ROUND(COALESCE(julianday('now') - julianday(CREATED_AT), 99), 0) AS DAYS_SINCE_LAST_UPDATE
FROM FILM_TMDB_STATS

UNION ALL

SELECT FILM_ID, 'FILM_URL_TITLE' AS TABLE_NAME, ROUND(COALESCE(julianday('now') - julianday(CREATED_AT), 99), 0) AS DAYS_SINCE_LAST_UPDATE
FROM FILM_URL_TITLE

UNION ALL

SELECT FILM_ID, 'IMDB_ID' AS TABLE_NAME, ROUND(COALESCE(julianday('now') - julianday(CREATED_AT), 99), 0) AS DAYS_SINCE_LAST_UPDATE
FROM IMDB_ID

UNION ALL

SELECT FILM_ID, 'TMDB_ID' AS TABLE_NAME, ROUND(COALESCE(julianday('now') - julianday(CREATED_AT), 99), 0) AS DAYS_SINCE_LAST_UPDATE
FROM TMDB_ID

)

SELECT
	
	a.FILM_ID
	,b.TABLE_NAME
	,b.DAYS_SINCE_LAST_UPDATE
	
FROM ALL_FILMS a
INNER JOIN UNION_TABLE b
ON a.FILM_ID = b.FILM_ID;

CREATE TABLE PORTRAIT_MISSING(
PERSON_ID INT,
CREATED_AT TIMESTAMP
);

CREATE TABLE "WATCHED" (
"FILM_ID" TEXT
);

CREATE TABLE "WATCHLIST" (
"FILM_ID" TEXT,
  "ADDED_DATE" TEXT
);

CREATE TABLE "FILM_TITLE" (
"FILM_ID" TEXT,
  "FILM_TITLE" TEXT,
  "LETTERBOXD_URL" TEXT
);

CREATE TABLE "FILM_YEAR" (
"FILM_ID" TEXT,
  "FILM_YEAR" INTEGER,
  "FILM_DECADE" TEXT
);

CREATE TABLE "PERSONAL_RANKING" (
"FILM_ID" TEXT,
  "FILM_POSITION" INTEGER
);

CREATE TABLE "PRIORITY_WATCHLIST" (
"FILM_ID" TEXT
);

CREATE TABLE "DIARY" (
"FILM_ID" TEXT,
  "WATCH_DATE" TEXT,
  "WATCH_ORDER_DAY" INTEGER,
  "FILM_RATING" REAL,
  "TAGS" TEXT,
  "FIRST_TIME_WATCH" INTEGER,
  "IS_NARRATIVE_FEATURE" INTEGER
);

CREATE TABLE "RATING_SCALING_DETAILS" (
"FILM_RATING_STR" TEXT,
  "FILM_RATING_BASIC" REAL,
  "RATING_COUNT" REAL,
  "MAX_RATING" REAL,
  "INCREMENT" REAL,
  "MAX_POSITION" REAL,
  "MIN_POSITION" REAL
);

CREATE TABLE "PERSONAL_RATING" (
"FILM_ID" TEXT,
  "FILM_RATING_BASIC" REAL,
  "FILM_RATING_SCALED" REAL,
  "FILM_RATING_PERCENT" REAL
);

CREATE TABLE "FILM_TOP_TEN_BOX_OFFICE_BY_YEAR" (
"FILM_ID" TEXT,
  "YEAR_BOX_OFFICE_POSITION" TEXT
);

CREATE TABLE "FILM_LETTERBOXD_TOP_250" (
"FILM_ID" TEXT,
  "TOP_250_POSITION" INTEGER
);

CREATE TABLE "FILM_ALGO_SCORE" (
"FILM_ID" TEXT,
  "FILM_TITLE" TEXT,
  "FILM_WATCH_COUNT" INTEGER,
  "FILM_TOP_250" REAL,
  "FILM_RATING" REAL,
  "LIKES_PER_WATCH" REAL,
  "FANS_PER_WATCH" REAL,
  "FILM_RUNTIME" REAL,
  "FILM_YEAR" INTEGER,
  "DIRECTOR_MEAN_RATING" REAL,
  "DIRECTOR_TOTAL_FILMS" REAL,
  "DIRECTOR_PERCENT_WATCHED" REAL,
  "ACTION" INTEGER,
  "ADVENTURE" INTEGER,
  "ANIMATION" INTEGER,
  "COMEDY" INTEGER,
  "CRIME" INTEGER,
  "DRAMA" INTEGER,
  "FAMILY" INTEGER,
  "FANTASY" INTEGER,
  "HISTORY" INTEGER,
  "HORROR" INTEGER,
  "MUSIC" INTEGER,
  "MYSTERY" INTEGER,
  "NONE" INTEGER,
  "ROMANCE" INTEGER,
  "SCIENCE-FICTION" INTEGER,
  "THRILLER" INTEGER,
  "TV-MOVIE" INTEGER,
  "WAR" INTEGER,
  "WESTERN" INTEGER,
  "2000S" REAL,
  "ABSURD" REAL,
  "ADVENTURER" REAL,
  "AFTERCREDITSSTINGER" REAL,
  "AGGRESSIVE" REAL,
  "ALIEN" REAL,
  "ALIEN INVASION" REAL,
  "ALIEN LIFE-FORM" REAL,
  "ALTERNATIVE REALITY" REAL,
  "AMBIGUOUS" REAL,
  "AMUSED" REAL,
  "AMUSEMENT PARK" REAL,
  "ANDROID" REAL,
  "ANIMAL HORROR" REAL,
  "ANTAGONISTIC" REAL,
  "ANTHROPOMORPHISM" REAL,
  "ANTI HERO" REAL,
  "ANXIOUS" REAL,
  "APOCALYPSE" REAL,
  "ARCHAEOLOGIST" REAL,
  "ARMY" REAL,
  "ARTIFICIAL INTELLIGENCE (A.I.)" REAL,
  "ASSERTIVE" REAL,
  "ASTRONAUT" REAL,
  "AUDACIOUS" REAL,
  "AWESTRUCK" REAL,
  "BABYSITTER" REAL,
  "BAFFLED" REAL,
  "BASED ON COMIC" REAL,
  "BASED ON SHORT" REAL,
  "BASEMENT" REAL,
  "BIBLE" REAL,
  "BITING" REAL,
  "BLACK MAGIC" REAL,
  "BODY HORROR" REAL,
  "BOLD" REAL,
  "BROTHER BROTHER RELATIONSHIP" REAL,
  "BRUTALITY" REAL,
  "CABIN" REAL,
  "CALLOUS" REAL,
  "CANNIBAL" REAL,
  "CAR RACE" REAL,
  "CASTLE" REAL,
  "CAUTIONARY" REAL,
  "CHAINSAW" REAL,
  "CHAOS" REAL,
  "CHEERFUL" REAL,
  "CHILD KIDNAPPING" REAL,
  "CHURCH" REAL,
  "CLOWN" REAL,
  "COMPLEX" REAL,
  "COMPUTER" REAL,
  "CONCERT" REAL,
  "CORPSE" REAL,
  "CREATURE" REAL,
  "CRITICAL" REAL,
  "CRUELTY" REAL,
  "CURIOUS" REAL,
  "CURSE" REAL,
  "CYBERPUNK" REAL,
  "CYBORG" REAL,
  "CYNICAL" REAL,
  "DEATH GAME" REAL,
  "DECAPITATION" REAL,
  "DEFIANT" REAL,
  "DELUSION" REAL,
  "DEMON" REAL,
  "DEMONIC POSSESSION" REAL,
  "DEPRESSING" REAL,
  "DESPERATE" REAL,
  "DIARY" REAL,
  "DISASTER" REAL,
  "DISASTER MOVIE" REAL,
  "DISGUSTED" REAL,
  "DISTURBED" REAL,
  "DOPPELGÄNGER" REAL,
  "DRACULA" REAL,
  "DRAMATIC" REAL,
  "DREAMS" REAL,
  "DUEL" REAL,
  "DURINGCREDITSSTINGER" REAL,
  "DYSTOPIA" REAL,
  "END OF THE WORLD" REAL,
  "EVIL" REAL,
  "EX-COP" REAL,
  "EXCITED" REAL,
  "EXHILARATED" REAL,
  "EXISTENTIALISM" REAL,
  "EXORCISM" REAL,
  "EXUBERANT" REAL,
  "FAKE IDENTITY" REAL,
  "FAMILIAR" REAL,
  "FANTASY WORLD" REAL,
  "FARCICAL" REAL,
  "FATE" REAL,
  "FEMALE VILLAIN" REAL,
  "FLYING" REAL,
  "FOLK HORROR" REAL,
  "FOREBODING" REAL,
  "FRANTIC" REAL,
  "FRIGHTENED" REAL,
  "FUTURE" REAL,
  "FUTURISTIC" REAL,
  "GAS STATION" REAL,
  "GOOD VERSUS EVIL" REAL,
  "GORE" REAL,
  "GOTHIC" REAL,
  "GOTHIC HORROR" REAL,
  "GRAND" REAL,
  "GRAVE" REAL,
  "GRIEF" REAL,
  "GRIM" REAL,
  "GUILT" REAL,
  "HACKER" REAL,
  "HALLOWEEN" REAL,
  "HALLUCINATION" REAL,
  "HARSH" REAL,
  "HAUNTED HOUSE" REAL,
  "HOMICIDE" REAL,
  "HOPEFUL" REAL,
  "HORRIFIED" REAL,
  "HORROR COMEDY" REAL,
  "IMMORTALITY" REAL,
  "INFECTION" REAL,
  "INSANITY" REAL,
  "INTENSE" REAL,
  "ISOLATION" REAL,
  "JOYFUL" REAL,
  "KILLER" REAL,
  "LABORATORY" REAL,
  "LAKE" REAL,
  "LOVING" REAL,
  "MACABRE" REAL,
  "MAD SCIENTIST" REAL,
  "MADNESS" REAL,
  "MAGIC" REAL,
  "MANIAC" REAL,
  "MANSION" REAL,
  "MARVEL CINEMATIC UNIVERSE (MCU)" REAL,
  "MASK" REAL,
  "MASS MURDER" REAL,
  "MASSACRE" REAL,
  "MEMORY LOSS" REAL,
  "MENTAL INSTITUTION" REAL,
  "MISCHIEVOUS" REAL,
  "MISSING CHILD" REAL,
  "MISSION" REAL,
  "MORGUE" REAL,
  "MOTEL" REAL,
  "MURDER MYSTERY" REAL,
  "MURDERER" REAL,
  "MUTANT" REAL,
  "MUTATION" REAL,
  "MYSTERIOUS" REAL,
  "NASA" REAL,
  "NEW ENGLAND" REAL,
  "NEW JERSEY" REAL,
  "NOSTALGIC" REAL,
  "NURSE" REAL,
  "OCCULT" REAL,
  "OMINOUS" REAL,
  "PARANOIA" REAL,
  "PHILADELPHIA, PENNSYLVANIA" REAL,
  "PHILOSOPHICAL" REAL,
  "PHILOSOPHY" REAL,
  "PLAGUE" REAL,
  "POSSESSION" REAL,
  "POWERFUL" REAL,
  "PREQUEL" REAL,
  "PROPHECY" REAL,
  "PROVOCATIVE" REAL,
  "PSYCHIC" REAL,
  "PSYCHOLOGICAL THRILLER" REAL,
  "PSYCHOLOGIST" REAL,
  "PSYCHOPATH" REAL,
  "PSYCHOTIC" REAL,
  "PSYCHOTRONIC" REAL,
  "PUPPET" REAL,
  "RACE AGAINST TIME" REAL,
  "REBOOT" REAL,
  "RESCUE MISSION" REAL,
  "RIDDLE" REAL,
  "RIDICULOUS" REAL,
  "RITUAL" REAL,
  "ROBOT" REAL,
  "SACRIFICE" REAL,
  "SADISM" REAL,
  "SATANISM" REAL,
  "SAVING THE WORLD" REAL,
  "SCIENTIST" REAL,
  "SECRET" REAL,
  "SECRET IDENTITY" REAL,
  "SECRET ORGANIZATION" REAL,
  "SECRET SOCIETY" REAL,
  "SELF SACRIFICE" REAL,
  "SEQUEL" REAL,
  "SERIAL KILLER" REAL,
  "SERIES OF MURDERS" REAL,
  "SHOCKING" REAL,
  "SHOTGUN" REAL,
  "SIGN LANGUAGES" REAL,
  "SLASHER" REAL,
  "SOCIOPATH" REAL,
  "SPACE" REAL,
  "SPACE MARINE" REAL,
  "SPACE OPERA" REAL,
  "SPACE TRAVEL" REAL,
  "SPACECRAFT" REAL,
  "SPIN OFF" REAL,
  "STEAMPUNK" REAL,
  "STOP MOTION" REAL,
  "SUMMER CAMP" REAL,
  "SUPERHERO" REAL,
  "SUPERHERO TEAM" REAL,
  "SUPERNATURAL" REAL,
  "SUPERNATURAL HORROR" REAL,
  "SUPERNATURAL POWER" REAL,
  "SURREALISM" REAL,
  "SURVIVAL HORROR" REAL,
  "SUSPENSEFUL" REAL,
  "TECHNOLOGY" REAL,
  "TELEKINESIS" REAL,
  "TELEPATHY" REAL,
  "TENSE" REAL,
  "TIME LOOP" REAL,
  "TIME TRAVEL" REAL,
  "TRAITOR" REAL,
  "TRANSFORMATION" REAL,
  "TRAUMA" REAL,
  "TREASURE HUNT" REAL,
  "UNDEAD" REAL,
  "UNDERWATER" REAL,
  "URBAN LEGEND" REAL,
  "VICTIM" REAL,
  "VIDEO NASTY" REAL,
  "VILLAIN" REAL,
  "VIOLENCE" REAL,
  "VIRTUAL REALITY" REAL,
  "VIRUS" REAL,
  "VOODOO" REAL,
  "VOYEURISM" REAL,
  "WHIMSICAL" REAL,
  "WHODUNIT" REAL,
  "WINTER" REAL,
  "WITCH" REAL,
  "WITCHCRAFT" REAL,
  "WITTY" REAL,
  "WIZARD" REAL,
  "WOODS" REAL,
  "ZOMBIE" REAL,
  "ZOMBIE APOCALYPSE" REAL,
  "FILM_RATING_SCALED" REAL,
  "I_VS_LB" REAL,
  "ALGO_SCORE" REAL
);

CREATE TABLE "FILM_SHAP_VALUES" (
"FILM_ID" TEXT,
  "BASE_VALUE" REAL,
  "FILM_RATING" REAL,
  "LIKES_PER_WATCH" REAL,
  "DIRECTOR_MEAN_RATING" REAL,
  "DIRECTOR_TOTAL_FILMS" REAL,
  "DIRECTOR_PERCENT_WATCHED" REAL,
  "ACTION" REAL,
  "ADVENTURE" REAL,
  "ANIMATION" REAL,
  "COMEDY" REAL,
  "CRIME" REAL,
  "DRAMA" REAL,
  "FAMILY" REAL,
  "FANTASY" REAL,
  "HISTORY" REAL,
  "HORROR" REAL,
  "MUSIC" REAL,
  "MYSTERY" REAL,
  "ROMANCE" REAL,
  "SCIENCE-FICTION" REAL,
  "THRILLER" REAL,
  "WAR" REAL,
  "ABSURD" REAL,
  "AFTERCREDITSSTINGER" REAL,
  "AGGRESSIVE" REAL,
  "ALIEN" REAL,
  "ALIEN INVASION" REAL,
  "AMUSED" REAL,
  "ANDROID" REAL,
  "ANTAGONISTIC" REAL,
  "ANTHROPOMORPHISM" REAL,
  "ANTI HERO" REAL,
  "ANXIOUS" REAL,
  "APOCALYPSE" REAL,
  "ARMY" REAL,
  "ARTIFICIAL INTELLIGENCE (A.I.)" REAL,
  "ASTRONAUT" REAL,
  "AWESTRUCK" REAL,
  "BASED ON COMIC" REAL,
  "BODY HORROR" REAL,
  "BROTHER BROTHER RELATIONSHIP" REAL,
  "BRUTALITY" REAL,
  "CANNIBAL" REAL,
  "CASTLE" REAL,
  "CAUTIONARY" REAL,
  "CHURCH" REAL,
  "CORPSE" REAL,
  "CREATURE" REAL,
  "CURSE" REAL,
  "CYBERPUNK" REAL,
  "DECAPITATION" REAL,
  "DEMON" REAL,
  "DEMONIC POSSESSION" REAL,
  "DISASTER" REAL,
  "DRAMATIC" REAL,
  "DREAMS" REAL,
  "DURINGCREDITSSTINGER" REAL,
  "DYSTOPIA" REAL,
  "EVIL" REAL,
  "EXORCISM" REAL,
  "FOLK HORROR" REAL,
  "FRIGHTENED" REAL,
  "FUTURE" REAL,
  "GORE" REAL,
  "GRIEF" REAL,
  "HALLOWEEN" REAL,
  "HALLUCINATION" REAL,
  "HAUNTED HOUSE" REAL,
  "HORRIFIED" REAL,
  "INSANITY" REAL,
  "INTENSE" REAL,
  "ISOLATION" REAL,
  "KILLER" REAL,
  "MAD SCIENTIST" REAL,
  "MAGIC" REAL,
  "MUTANT" REAL,
  "MYSTERIOUS" REAL,
  "NURSE" REAL,
  "OCCULT" REAL,
  "PARANOIA" REAL,
  "POSSESSION" REAL,
  "PREQUEL" REAL,
  "PSYCHOLOGICAL THRILLER" REAL,
  "PSYCHOPATH" REAL,
  "ROBOT" REAL,
  "SADISM" REAL,
  "SAVING THE WORLD" REAL,
  "SCIENTIST" REAL,
  "SECRET IDENTITY" REAL,
  "SEQUEL" REAL,
  "SERIAL KILLER" REAL,
  "SERIES OF MURDERS" REAL,
  "SHOCKING" REAL,
  "SLASHER" REAL,
  "SPACE" REAL,
  "SPACE MARINE" REAL,
  "SPACE OPERA" REAL,
  "SPACE TRAVEL" REAL,
  "SPACECRAFT" REAL,
  "SUPERHERO" REAL,
  "SUPERNATURAL" REAL,
  "SUPERNATURAL HORROR" REAL,
  "SUPERNATURAL POWER" REAL,
  "SURREALISM" REAL,
  "SURVIVAL HORROR" REAL,
  "SUSPENSEFUL" REAL,
  "TENSE" REAL,
  "TIME TRAVEL" REAL,
  "TRANSFORMATION" REAL,
  "VILLAIN" REAL,
  "VIOLENCE" REAL,
  "VIRUS" REAL,
  "WHIMSICAL" REAL,
  "WHODUNIT" REAL,
  "WINTER" REAL,
  "WITCH" REAL,
  "WOODS" REAL,
  "ZOMBIE" REAL,
  "PREDICTION" REAL
);

CREATE TABLE "precomputed_watchlist" (
"FILM_ID" TEXT,
  "FILM_TITLE" TEXT,
  "LETTERBOXD_URL" TEXT,
  "SEEN" INTEGER,
  "FILM_WATCH_COUNT" INTEGER,
  "FILM_TOP_250" REAL,
  "FILM_RATING" REAL,
  "FILM_LIKES_COUNT" INTEGER,
  "FILM_FAN_COUNT" INTEGER,
  "STREAMING" TEXT,
  "STREAMING_SERVICES" TEXT,
  "RENTABLE" TEXT,
  "WATCHABLE" TEXT,
  "MIN_RENTAL_PRICE" REAL,
  "FILM_RUNTIME" INTEGER,
  "FILM_DECADE" TEXT,
  "FILM_YEAR" INTEGER,
  "FILM_GENRE" TEXT,
  "GENRE_SCORE" REAL
);

CREATE TABLE "precomputed_all_films" (
"FILM_ID" TEXT,
  "FILM_TITLE" TEXT,
  "LETTERBOXD_URL" TEXT,
  "SEEN" INTEGER,
  "FILM_WATCH_COUNT" INTEGER,
  "FILM_TOP_250" REAL,
  "FILM_RATING" REAL,
  "RATED" INTEGER,
  "FILM_RATING_SCALED" REAL,
  "MY_RATING_VS_LB" REAL,
  "MY_RATING_VS_LB_ABS" REAL,
  "FILM_LIKES_COUNT" INTEGER,
  "LIKES_PER_WATCH" REAL,
  "FILM_FAN_COUNT" INTEGER,
  "FANS_PER_WATCH" REAL,
  "STREAMING" TEXT,
  "STREAMING_SERVICES" TEXT,
  "RENTABLE" TEXT,
  "WATCHABLE" TEXT,
  "MIN_RENTAL_PRICE" REAL,
  "FILM_RUNTIME" REAL,
  "FILM_DECADE" TEXT,
  "FILM_YEAR" INTEGER,
  "FILM_RELEASE_DATE" TEXT,
  "RELEASED" INTEGER,
  "FILM_GENRE" TEXT,
  "ALL_FILM_GENRES" TEXT,
  "ALGO_SCORE" REAL,
  "ALGO_SCORE_VS_LB" REAL,
  "PRIORITY_WATCHLIST" INTEGER
);

CREATE TABLE "precomputed_year_completion" (
"FILM_YEAR" INTEGER,
  "TOTAL_FILMS" INTEGER,
  "FILMS_WATCHED" INTEGER,
  "PERCENT_WATCHED" REAL,
  "FILMS_RATED" INTEGER,
  "PERCENT_RATED" REAL,
  "PERCENT_WATCHES_RATED" REAL,
  "LETTERBOXD_RATING_MEAN" REAL,
  "MY_RATING_MEAN" REAL,
  "LETTERBOXD_WATCH_COUNT" REAL,
  "LETTERBOXD_WATCHES_PER_FILM" REAL,
  "LETTERBOXD_WATCH_COUNT_WATCHED" REAL,
  "LETTERBOXD_WATCH_COUNT_WATCHED_PERCENT" REAL
);

CREATE TABLE "precomputed_genre_completion" (
"FILM_GENRE" TEXT,
  "FILMS_WATCHED" INTEGER,
  "TOTAL_FILMS" INTEGER,
  "PERCENT_WATCHED" REAL
);

CREATE TABLE "precomputed_keyword_completion" (
"KEYWORD_ID" INTEGER,
  "KEYWORD" TEXT,
  "TOTAL_FILMS" INTEGER,
  "FILMS_WATCHED" INTEGER,
  "PERCENT_WATCHED" REAL,
  "FILMS_RATED" INTEGER,
  "PERCENT_RATED" REAL,
  "MEAN_RATING" REAL
);

CREATE TABLE "precomputed_keyword_film_level" (
"FILM_TITLE" TEXT,
  "KEYWORD" TEXT,
  "WATCHED" INTEGER,
  "FILM_YEAR" INTEGER,
  "FILM_WATCH_COUNT" INTEGER,
  "FILM_RATING" REAL,
  "FILM_RATING_SCALED" REAL
);

CREATE TABLE "precomputed_director_completion" (
"PERSON_ID" INTEGER,
  "DIRECTOR_NAME" TEXT,
  "TOTAL_FILMS" INTEGER,
  "FILMS_WATCHED" INTEGER,
  "PERCENT_WATCHED" REAL,
  "FILMS_RATED" INTEGER,
  "PERCENT_RATED" REAL,
  "MY_RATING_MEAN" REAL,
  "LETTERBOXD_RATING_MEAN" REAL,
  "LETTERBOXD_WATCH_COUNT" INTEGER,
  "LETTERBOXD_WATCHES_PER_FILM" REAL,
  "TOP_FIVE_RATING" REAL
);

CREATE TABLE "precomputed_director_film_level" (
"FILM_ID" TEXT,
  "FILM_TITLE" TEXT,
  "LETTERBOXD_URL" TEXT,
  "PERSON_ID" REAL,
  "DIRECTOR_NAME" TEXT,
  "WATCHED" INTEGER,
  "RATED" INTEGER,
  "FILM_YEAR" INTEGER,
  "FILM_WATCH_COUNT" INTEGER,
  "FILM_RATING" REAL,
  "FILM_RATING_SCALED" REAL,
  "ALGO_SCORE" REAL,
  "FILM_POSITION" REAL
);

CREATE TABLE "precomputed_director_debut" (
"FILM_ID" TEXT,
  "FILM_TITLE" TEXT,
  "FILM_RELEASE_DATE" TEXT,
  "PERSON_ID" INTEGER,
  "DIRECTOR_NAME" TEXT,
  "JOB" TEXT,
  "TOTAL_FILMS" INTEGER,
  "FILM_NUMBER" INTEGER,
  "DEBUT_FILM_RELEASE_DATE" TEXT,
  "DAYS_SINCE_DEBUT" REAL,
  "AGE_IN_DAYS" REAL
);

CREATE TABLE "precomputed_director_topfive" (
"PERSON_ID" INTEGER,
  "DIRECTOR_NAME" TEXT,
  "TOTAL_FILMS" INTEGER,
  "FILMS_RATED" INTEGER,
  "TOP_FIVE_RATING" REAL
);

CREATE TABLE "precomputed_director_sparklines" (
"PERSON_ID" INTEGER,
  "DIRECTOR_NAME" TEXT,
  "LETTERBOXD_DAYS" REAL,
  "CUMULATIVE_FILMS" INTEGER
);

CREATE TABLE "precomputed_actor_completion" (
"PERSON_ID" INTEGER,
  "ACTOR_NAME" TEXT,
  "TOTAL_FILMS" INTEGER,
  "FILMS_WATCHED" INTEGER,
  "PERCENT_WATCHED" REAL,
  "FILMS_RATED" INTEGER,
  "PERCENT_RATED" REAL,
  "MY_RATING_MEAN" REAL,
  "LETTERBOXD_RATING_MEAN" REAL,
  "LETTERBOXD_WATCH_COUNT" INTEGER,
  "LETTERBOXD_WATCHES_PER_FILM" REAL
);

CREATE TABLE "precomputed_actor_film_level" (
"FILM_ID" TEXT,
  "FILM_TITLE" TEXT,
  "LETTERBOXD_URL" TEXT,
  "PERSON_ID" INTEGER,
  "ACTOR_NAME" TEXT,
  "WATCHED" INTEGER,
  "RATED" INTEGER,
  "FILM_YEAR" INTEGER,
  "FILM_WATCH_COUNT" INTEGER,
  "FILM_RATING" REAL,
  "FILM_RATING_SCALED" REAL,
  "ALGO_SCORE" REAL,
  "FILM_POSITION" REAL
);

CREATE TABLE "precomputed_top_actor_film_level" (
"FILM_ID" TEXT,
  "PERSON_ID" INTEGER,
  "ACTOR_NAME" TEXT
);

CREATE TABLE "precomputed_actor_debut" (
"FILM_ID" TEXT,
  "FILM_TITLE" TEXT,
  "FILM_RELEASE_DATE" TEXT,
  "PERSON_ID" INTEGER,
  "ACTOR_NAME" TEXT,
  "TOTAL_FILMS" INTEGER,
  "FILM_NUMBER" INTEGER,
  "DEBUT_FILM_RELEASE_DATE" TEXT,
  "DAYS_SINCE_DEBUT" REAL,
  "AGE_IN_DAYS" REAL
);

CREATE TABLE "precomputed_actor_sparklines" (
"PERSON_ID" INTEGER,
  "ACTOR_NAME" TEXT,
  "LETTERBOXD_DAYS" REAL,
  "CUMULATIVE_FILMS" INTEGER
);

CREATE TABLE "precomputed_film_score" (
"FILM_ID" TEXT,
  "FILM_TITLE" TEXT,
  "FILM_GENRE" TEXT,
  "FILM_WATCH_COUNT" INTEGER,
  "FILM_RATING" REAL,
  "FILM_SCORE" REAL,
  "WATCHED" INTEGER,
  "STREAMING" TEXT,
  "STREAMING_SERVICES" TEXT
);

CREATE TABLE "precomputed_diary_agg" (
"WATCH_DATE" TEXT,
  "MOVIE_COUNT" INTEGER,
  "MOVIE_RATING" REAL
);

CREATE TABLE "precomputed_diary_detail" (
"WATCH_DATE" TEXT,
  "FILM_TITLE" TEXT,
  "FIRST_TIME_WATCH" INTEGER,
  "FILM_RATING_SCALED" REAL
);

CREATE TABLE "precomputed_top_keyword" (
"FILM_ID" TEXT,
  "KEYWORD_ID" INTEGER,
  "KEYWORD" TEXT
);

CREATE TABLE "precomputed_watched_feature_stats" (
"FILM_ID" TEXT,
  "FILM_TITLE" TEXT,
  "FILM_GENRE" TEXT,
  "ALL_FILM_GENRES" TEXT,
  "FILM_LANGUAGE" TEXT,
  "LETTERBOXD_WATCH_COUNT" INTEGER,
  "LETTERBOXD_FAN_COUNT" INTEGER,
  "LETTERBOXD_LIKES_COUNT" INTEGER,
  "LETTERBOXD_REVIEW_COUNT" INTEGER,
  "LETTERBOXD_LIST_COUNT" INTEGER,
  "LETTERBOXD_TOP_250" REAL,
  "LETTERBOXD_RATING" REAL,
  "LETTERBOXD_RATING_COUNT" REAL,
  "FILM_RUNTIME" REAL,
  "TMDB_FILM_POPULARITY" REAL,
  "TMDB_VOTE_AVERAGE" REAL,
  "TMDB_VOTE_COUNT" REAL,
  "FILM_YEAR" INTEGER,
  "FILM_DECADE" TEXT,
  "FILM_RATING_BASIC" REAL,
  "FILM_RATING_SCALED" REAL
);

CREATE TABLE "precomputed_collection_completion" (
"COLLECTION_NAME" TEXT,
  "TOTAL_FILMS" INTEGER,
  "FILMS_WATCHED" INTEGER,
  "PERCENT_WATCHED" REAL,
  "FILMS_RATED" INTEGER,
  "PERCENT_RATED" REAL,
  "MEAN_RATING" REAL
);

CREATE TABLE "precomputed_collection_film_level" (
"COLLECTION_NAME" TEXT,
  "FILM_TITLE" TEXT,
  "FILM_YEAR" INTEGER,
  "FILM_WATCH_COUNT" INTEGER,
  "FILM_RATING" REAL,
  "WATCHED" INTEGER,
  "RATED" INTEGER,
  "FILM_RATING_SCALED" REAL
);

CREATE TABLE "precomputed_collections_close_to_completion" (
"COLLECTION_NAME" TEXT,
  "FILM_TITLE" TEXT,
  "FILM_YEAR" INTEGER,
  "FILM_WATCH_COUNT" INTEGER,
  "FILM_RATING" REAL,
  "TOTAL_FILMS" INTEGER,
  "FILMS_TO_COMPLETE" INTEGER,
  "COLLECTION_RATING" REAL
);

CREATE TABLE "precomputed_diagnostics" (
"FILM_ID" TEXT,
  "FILM_TITLE" TEXT,
  "FILM_WATCH_COUNT" REAL,
  "MEAN_DAYS_SINCE_LAST_UPDATE" REAL,
  "FILM_LETTERBOXD_STATS" REAL,
  "FILM_STREAMING_SERVICES" REAL,
  "FILM_TMDB_STATS" REAL,
  "CONTENT_TYPE" REAL,
  "FILM_CAST" REAL,
  "FILM_COLLECTIONS" REAL,
  "FILM_CREW" REAL,
  "FILM_FINANCIALS" REAL,
  "FILM_GENRE" REAL,
  "FILM_KEYWORDS" REAL,
  "FILM_LANGUAGE" REAL,
  "FILM_RELEASE_INFO" REAL,
  "FILM_RUNTIME" REAL,
  "FILM_URL_TITLE" REAL,
  "FILM_YEAR" TEXT,
  "IMDB_ID" REAL,
  "TMDB_ID" REAL
);

