SELECT a.*, CASE WHEN b.FILM_ID IS NOT NULL THEN 1 ELSE 0 END AS WATCHED, c.LETTERBOXD_URL, d.FILM_POSITION
FROM FILM_ALGO_SCORE a
LEFT JOIN WATCHED b ON a.FILM_ID = b.FILM_ID
LEFT JOIN FILM_TITLE c ON a.FILM_ID = c.FILM_ID
LEFT JOIN PERSONAL_RANKING d ON a.FILM_ID = d.FILM_ID 