WITH BASE_TABLE AS (
    SELECT a.FILM_ID,
           c.FILM_TITLE,
           d.FILM_RATING,
           e.FILM_RATING_SCALED,
           CASE WHEN e.FILM_RATING_SCALED IS NOT NULL THEN 1 ELSE 0 END AS RATED
    FROM ALL_FILMS a
    LEFT JOIN CONTENT_TYPE b ON a.FILM_ID = b.FILM_ID
    LEFT JOIN FILM_TITLE c ON a.FILM_ID = c.FILM_ID
    LEFT JOIN FILM_LETTERBOXD_STATS d ON a.FILM_ID = d.FILM_ID
    LEFT JOIN PERSONAL_RATING e ON a.FILM_ID = e.FILM_ID
    WHERE b.CONTENT_TYPE = 'movie'
),
RECENTLY_WATCHED AS (
    SELECT FILM_ID, 1 AS RECENTLY_WATCHED
    FROM DIARY
    WHERE WATCH_DATE >= date('now', '-14 days')
      AND IS_NARRATIVE_FEATURE = 1
),
DIRECTOR_TABLE AS (
    SELECT FILM_ID,
           GROUP_CONCAT(DIRECTOR_NAME, ', ') AS DIRECTOR_NAME
    FROM (
        SELECT a.FILM_ID,
               c.PERSON_NAME AS DIRECTOR_NAME
        FROM ALL_FEATURE_FILMS a
        LEFT JOIN FILM_CREW b ON a.FILM_ID = b.FILM_ID
        LEFT JOIN PERSON_INFO c ON b.PERSON_ID = c.PERSON_ID
        WHERE b.job = 'Director'
          AND c.PERSON_NAME IS NOT NULL
    )
    GROUP BY FILM_ID
)
SELECT a.FILM_ID,
       b.FILM_TITLE,
       g.FILM_RATING_SCALED,
       i.FILM_POSITION,
       c.FILM_WATCH_COUNT,
       k.TOP_250_POSITION   AS FILM_TOP_250,
       c.FILM_RATING,
       COALESCE(1.0*c.FILM_LIKES_COUNT/c.FILM_WATCH_COUNT, 0.0) AS LIKES_PER_WATCH,
       COALESCE(1.0*c.FILM_FAN_COUNT/c.FILM_WATCH_COUNT, 0.0)  AS FANS_PER_WATCH,
       h.DIRECTOR_NAME,
       d.FILM_RUNTIME,
       f.FILM_YEAR,
       f.FILM_DECADE,
       e.FILM_GENRE,
       e.ALL_FILM_GENRES,
       l.ACTION                 AS GENRE_ACTION,
       l.ADVENTURE              AS GENRE_ADVENTURE,
       l.ANIMATION              AS GENRE_ANIMATION,
       l.COMEDY                 AS GENRE_COMEDY,
       l.CRIME                  AS GENRE_CRIME,
       l.DRAMA                  AS GENRE_DRAMA,
       l.FAMILY                 AS GENRE_FAMILY,
       l.FANTASY                AS GENRE_FANTASY,
       l.HISTORY                AS GENRE_HISTORY,
       l.HORROR                 AS GENRE_HORROR,
       l.MUSIC                  AS GENRE_MUSIC,
       l.MYSTERY                AS GENRE_MYSTERY,
       l.ROMANCE                AS GENRE_ROMANCE,
       l."SCIENCE-FICTION"     AS GENRE_SCIENCE_FICTION,
       l.THRILLER               AS GENRE_THRILLER,
       l.WAR                    AS GENRE_WAR,
       l.WESTERN                AS GENRE_WESTERN,
       j.COLLECTION_NAME,
       COALESCE(m.RECENTLY_WATCHED, 0) AS RECENTLY_WATCHED,
       CASE WHEN n.FILM_ID IS NOT NULL THEN 1 ELSE 0 END       AS VALID_TITLE
FROM ALL_FILMS a
LEFT JOIN FILM_TITLE b ON a.FILM_ID = b.FILM_ID
LEFT JOIN FILM_LETTERBOXD_STATS c ON a.FILM_ID = c.FILM_ID
LEFT JOIN FILM_RUNTIME d ON a.FILM_ID = d.FILM_ID
LEFT JOIN FILM_GENRE e ON a.FILM_ID = e.FILM_ID
LEFT JOIN FILM_YEAR f ON a.FILM_ID = f.FILM_ID
LEFT JOIN PERSONAL_RATING g ON a.FILM_ID = g.FILM_ID
LEFT JOIN DIRECTOR_TABLE h ON a.FILM_ID = h.FILM_ID
LEFT JOIN PERSONAL_RANKING i ON a.FILM_ID = i.FILM_ID
LEFT JOIN FILM_COLLECTIONS j ON a.FILM_ID = j.FILM_ID
LEFT JOIN FILM_LETTERBOXD_TOP_250 k ON a.FILM_ID = k.FILM_ID
LEFT JOIN FILM_ALGO_SCORE l ON a.FILM_ID = l.FILM_ID
LEFT JOIN RECENTLY_WATCHED m ON a.FILM_ID = m.FILM_ID
LEFT JOIN ALL_FEATURE_FILMS n ON a.FILM_ID = n.FILM_ID 