SELECT FILM_ID, COALESCE(MAX(CAST_ORDER), 0) AS CAST_SIZE FROM (

SELECT

	 a.FILM_ID
	 ,b.CAST_ORDER
	 ,COALESCE(julianday('now') - julianday(b.CREATED_AT), 99) AS DAYS_SINCE_LAST_UPDATE

FROM ALL_FILMS a

LEFT JOIN FILM_CAST b
ON a.FILM_ID = b.FILM_ID

LEFT JOIN TMDB_ID c
ON a.FILM_ID = c.FILM_ID

WHERE DAYS_SINCE_LAST_UPDATE > 7
AND c.VALID = 1

) GROUP BY FILM_ID
HAVING CAST_SIZE = 0 