WITH BASE_TABLE AS (

	SELECT COLLECTION_ID, COUNT(DISTINCT COLLECTION_NAME) AS ISSUE
	FROM FILM_COLLECTIONS
	GROUP BY COLLECTION_ID
	HAVING ISSUE > 1
	
	)
	
SELECT

	b.FILM_ID
	
FROM BASE_TABLE a
LEFT JOIN FILM_COLLECTIONS b
ON a.COLLECTION_ID = b.COLLECTION_ID 