WITH BASE_TABLE AS (

    SELECT

        a.FILM_ID
        ,d.FILM_TITLE
        ,b.PERSON_ID
        ,e.PERSON_NAME AS DIRECTOR_NAME
        ,CASE WHEN c.FILM_ID IS NULL THEN 0 ELSE 1 END AS WATCHED
        ,f.FILM_RATING_SCALED
        ,CASE WHEN f.FILM_RATING_SCALED IS NULL THEN 0 ELSE 1 END AS RATED

    FROM ALL_FEATURE_FILMS a

    LEFT JOIN FILM_CREW b ON a.FILM_ID = b.FILM_ID
    LEFT JOIN WATCHED c ON a.FILM_ID = c.FILM_ID
    LEFT JOIN FILM_TITLE d ON a.FILM_ID = d.FILM_ID
    LEFT JOIN PERSON_INFO e ON b.PERSON_ID = e.PERSON_ID
    LEFT JOIN PERSONAL_RATING f ON a.FILM_ID = f.FILM_ID

    WHERE b.JOB = 'Director'
        
    )
      
, DIRECTOR_RATINGS AS (

    SELECT PERSON_ID,
           DIRECTOR_NAME,
           COUNT(*) AS TOTAL_FILMS,
           SUM(WATCHED) AS FILMS_WATCHED,
           AVG(WATCHED) AS PERCENT_WATCHED,
           AVG(FILM_RATING_SCALED) AS MEAN_RATING,
           SUM(RATED) AS FILMS_RATED,
           AVG(RATED) AS PERCENT_RATED
    FROM BASE_TABLE
    GROUP BY PERSON_ID, DIRECTOR_NAME
    HAVING TOTAL_FILMS >= 3
       AND FILMS_WATCHED > 1
       AND FILMS_RATED > 1
       AND MEAN_RATING NOT NULL
       AND PERCENT_RATED >= .2
)
, DIRECTOR_WATCH_STATS AS (
    SELECT PERSON_ID,
           DIRECTOR_NAME,
           COUNT(*) AS TOTAL_FILMS,
           AVG(WATCHED) AS PERCENT_WATCHED
    FROM BASE_TABLE
    GROUP BY PERSON_ID, DIRECTOR_NAME
)
, MEAN_RATING AS ( SELECT AVG(MEAN_RATING) AS MEAN_TOTAL_RATING FROM DIRECTOR_RATINGS )
, FILM_DIRECTOR_LEVEL AS (
    SELECT a.FILM_ID,
           a.FILM_TITLE,
           a.PERSON_ID,
           a.DIRECTOR_NAME,
           COALESCE(b.MEAN_RATING, (SELECT MEAN_TOTAL_RATING FROM MEAN_RATING)) AS DIRECTOR_MEAN_RATING,
           COALESCE(c.TOTAL_FILMS, 0) AS DIRECTOR_TOTAL_FILMS,
           COALESCE(c.PERCENT_WATCHED, 0) AS DIRECTOR_PERCENT_WATCHED
     FROM BASE_TABLE a
     LEFT JOIN DIRECTOR_RATINGS b  ON a.PERSON_ID = b.PERSON_ID
     LEFT JOIN DIRECTOR_WATCH_STATS c ON a.PERSON_ID = c.PERSON_ID
)
SELECT FILM_ID,
       AVG(DIRECTOR_MEAN_RATING) AS DIRECTOR_MEAN_RATING,
       AVG(DIRECTOR_TOTAL_FILMS) AS DIRECTOR_TOTAL_FILMS,
       AVG(DIRECTOR_PERCENT_WATCHED) AS DIRECTOR_PERCENT_WATCHED
FROM FILM_DIRECTOR_LEVEL
GROUP BY FILM_ID 