SELECT

	 a.FILM_ID
	,b.FILM_GENRE
	,COALESCE(julianday('now') - julianday(b.CREATED_AT), 99) AS DAYS_SINCE_LAST_UPDATE

FROM ALL_FILMS a

LEFT JOIN FILM_GENRE b
ON a.FILM_ID = b.FILM_ID

WHERE b.FILM_ID IS NULL
OR b.FILM_GENRE = ""
OR b.FILM_GENRE IS NULL
AND DAYS_SINCE_LAST_UPDATE > 7 