SELECT

	 a.FILM_ID
	,COALESCE(julianday('now') - julianday(b.CREATED_AT), 99) AS DAYS_SINCE_LAST_UPDATE_IMDB
    ,COALESCE(julianday('now') - julianday(c.CREATED_AT), 99) AS DAYS_SINCE_LAST_UPDATE_TMDB

FROM ALL_FILMS a

LEFT JOIN IMDB_ID b
ON a.FILM_ID = b.FILM_ID

LEFT JOIN TMDB_ID c
ON a.FILM_ID = c.FILM_ID

WHERE b.IMDB_ID IS NULL
AND DAYS_SINCE_LAST_UPDATE_IMDB > 3
AND DAYS_SINCE_LAST_UPDATE_TMDB > 3
AND c.VALID = 1 