SELECT

	 a.FILM_ID
	 ,COALESCE(julianday('now') - julianday(b.CREATED_AT), 99) AS DAYS_SINCE_LAST_UPDATE

FROM ALL_RELEASED_FILMS a

LEFT JOIN FILM_LETTERBOXD_STATS b
ON a.FILM_ID = b.FILM_ID

WHERE COALESCE(b.FILM_WATCH_COUNT, 0) = 0
AND DAYS_SINCE_LAST_UPDATE > 7 