SELECT
	 a.FILM_ID
	,COALESCE(julianday('now') - julianday(b.CREATED_AT), 99) AS DAYS_SINCE_LAST_UPDATE
	
FROM ALL_RELEASED_FILMS a
LEFT JOIN FILM_LETTERBOXD_STATS b
ON a.FILM_ID = b.FILM_ID

ORDER BY DAYS_SINCE_LAST_UPDATE DESC 