WITH DAYS_SINCE_LAST_STREAMING_UPDATE AS (

SELECT FILM_ID, ROUND(AVG(DAYS_SINCE_LAST_UPDATE), 0) AS DAYS_SINCE_LAST_UPDATE 
FROM ( SELECT FILM_ID, ROUND(COALESCE(julianday('now') - julianday(CREATED_AT), 99), 0) AS DAYS_SINCE_LAST_UPDATE FROM FILM_STREAMING_SERVICES )
GROUP BY FILM_ID

)

SELECT a.FILM_ID
FROM FILM_ALGO_SCORE a
LEFT JOIN DAYS_SINCE_LAST_STREAMING_UPDATE b
ON a.FILM_ID = b.FILM_ID
ORDER BY COALESCE(a.ALGO_SCORE,0.01) * COALESCE(a.ALGO_SCORE,0.01) * COALESCE(b.DAYS_SINCE_LAST_UPDATE, 365) DESC 