WITH BASE_TABLE AS (

	SELECT
	
		a.FILM_ID
		,b.FILM_TITLE
		,c.FILM_WATCH_COUNT
		,ROUND(COALESCE(julianday('now') - julianday(c.CREATED_AT), 99), 0) AS DAYS_SINCE_LAST_UPDATE
	
	FROM ALL_FEATURE_FILMS a
	LEFT JOIN FILM_TITLE b
	ON a.FILM_ID = b.FILM_ID
	LEFT JOIN FILM_LETTERBOXD_STATS c
	ON a.FILM_ID = c.FILM_ID

	)
	
SELECT
	*
	,ROUND(POWER(FILM_WATCH_COUNT, 1) * POWER(DAYS_SINCE_LAST_UPDATE, 1.5)) AS SORT_KEY
FROM BASE_TABLE
ORDER BY SORT_KEY DESC 