WITH BASE_TABLE AS (

    SELECT DISTINCT b.PERSON_ID, c.KNOWN_FOR_DEPARTMENT, a.FILM_ID, a.FILM_WATCH_COUNT
    FROM FILM_LETTERBOXD_STATS a
    LEFT JOIN FILM_CREW b ON a.FILM_ID = b.FILM_ID
    LEFT JOIN PERSON_INFO c ON b.PERSON_ID = c.PERSON_ID
    WHERE b.PERSON_ID > 0
    AND c.KNOWN_FOR_DEPARTMENT IS NOT NULL

)

SELECT PERSON_ID, SUM(FILM_WATCH_COUNT) AS TOTAL_WATCH_COUNT
FROM BASE_TABLE
GROUP BY PERSON_ID
ORDER BY TOTAL_WATCH_COUNT DESC 