WITH FILM_PERSON_INFO AS (      
   
   SELECT
       a.FILM_ID,
       b.FILM_WATCH_COUNT,
       c.PERSON_ID
   FROM ALL_RELEASED_FILMS a
   LEFT JOIN FILM_LETTERBOXD_STATS b ON a.FILM_ID = b.FILM_ID
   LEFT JOIN FILM_CAST c ON a.FILM_ID = c.FILM_ID
   
   UNION ALL 
   
   SELECT
       a.FILM_ID,
       b.FILM_WATCH_COUNT,
       c.PERSON_ID
   FROM ALL_RELEASED_FILMS a
   LEFT JOIN FILM_LETTERBOXD_STATS b ON a.FILM_ID = b.FILM_ID
   LEFT JOIN FILM_CREW c ON a.FILM_ID = c.FILM_ID
   WHERE c.JOB = 'Director'
   
 )
 
 SELECT 
     a.PERSON_ID,
     b.PERSON_NAME,
     SUM(a.FILM_WATCH_COUNT) AS TOTAL_WATCHES
 FROM FILM_PERSON_INFO a
 LEFT JOIN PERSON_INFO b ON a.PERSON_ID = b.PERSON_ID
 WHERE a.PERSON_ID > 0
 AND b.PERSON_NAME IS NULL
 GROUP BY a.PERSON_ID, a.FILM_ID
 ORDER BY TOTAL_WATCHES DESC 