SELECT

	 a.FILM_ID
    ,COALESCE(julianday('now') - julianday(b.CREATED_AT), 99) AS DAYS_SINCE_LAST_UPDATE

FROM ALL_FILMS a

LEFT JOIN FILM_RUNTIME b
ON a.FILM_ID = b.FILM_ID

LEFT JOIN TMDB_ID c
ON a.FILM_ID = c.FILM_ID

WHERE COALESCE(b.FILM_RUNTIME, 0) = 0
AND c.VALID = 1
AND DAYS_SINCE_LAST_UPDATE > 7 