SELECT

	 a.FILM_ID
    ,COALESCE(julianday('now') - julianday(c.CREATED_AT), 99) AS DAYS_SINCE_LAST_UPDATE

FROM ALL_FILMS a

LEFT JOIN FILM_TITLE b
ON a.FILM_ID = b.FILM_ID

LEFT JOIN FILM_URL_TITLE c
ON a.FILM_ID = c.FILM_ID

WHERE b.FILM_TITLE IS NULL
OR b.FILM_TITLE = ""
OR c.FILM_URL_TITLE IS NULL
OR c.FILM_URL_TITLE = ""
AND DAYS_SINCE_LAST_UPDATE > 7 