SELECT

	 a.FILM_ID
	 ,COALESCE(julianday('now') - julianday(b.CREATED_AT), 99) AS DAYS_SINCE_LAST_UPDATE

FROM ALL_FILMS a

LEFT JOIN TMDB_ID b
ON a.FILM_ID = b.FILM_ID

WHERE b.TMDB_ID IS NULL
AND DAYS_SINCE_LAST_UPDATE > 3
AND b.VALID = 1 