SELECT

	 a.FILM_ID
	 ,COALESCE(julianday('now') - julianday(b.CREATED_AT), 99) AS DAYS_SINCE_LAST_UPDATE

FROM ALL_RELEASED_FILMS a

LEFT JOIN FILM_TMDB_STATS b
ON a.FILM_ID = b.FILM_ID

LEFT JOIN TMDB_ID c
ON a.FILM_ID = c.FILM_ID

WHERE b.FILM_POPULARITY IS NULL
AND DAYS_SINCE_LAST_UPDATE > 7
AND c.VALID = 1 