SELECT
                                   
	a.FILM_ID
	
FROM ALL_FILMS a

LEFT JOIN FILM_YEAR b
ON a.FILM_ID = b.FILM_ID

LEFT JOIN FILM_RELEASE_INFO c
ON a.FILM_ID = c.FILM_ID

LEFT JOIN FILM_LAST_UPDATED d
ON a.FILM_ID = d.FILM_ID

LEFT JOIN CONTENT_TYPE e
ON a.FILM_ID = e.FILM_ID

WHERE e.CONTENT_TYPE = 'movie'
AND COALESCE(c.FILM_STATUS, "None") != "Released"
AND b.FILM_YEAR >= {}
AND d.MEAN_DAYS_SINCE_LAST_UPDATE > 7
                                 
ORDER BY d.MEAN_DAYS_SINCE_LAST_UPDATE DESC 